"""Add payment_date column to invoices

Revision ID: 89d2b829d1a5
Revises: 9ee88e59f721
Create Date: 2024-11-26 14:36:36.285270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2b829d1a5'
down_revision = '9ee88e59f721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
