"""Add unique constraint on lease_id and email for tenants

Revision ID: 853ce76a8bfe
Revises: 89d2b829d1a5
Create Date: 2024-11-26 23:07:59.941121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853ce76a8bfe'
down_revision = '89d2b829d1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_tenant_per_lease', ['lease_id', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('unique_tenant_per_lease', type_='unique')

    # ### end Alembic commands ###
