"""remove email unique constraint from tenanat model

Revision ID: 56ad0a9034b9
Revises: 853ce76a8bfe
Create Date: 2024-11-27 14:15:59.309114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ad0a9034b9'
down_revision = '853ce76a8bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_email', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_email', ['email'])

    # ### end Alembic commands ###
