"""remove invoice number column

Revision ID: b0af5e994f95
Revises: 4245a8e795eb
Create Date: 2024-11-22 23:12:49.006813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af5e994f95'
down_revision = '4245a8e795eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('lease_number')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('square_feet',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('square_feet',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
