"""add lease_doc column to lease model

Revision ID: 3a911685c109
Revises: 5e0f2f775aa8
Create Date: 2024-12-03 14:47:10.068224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a911685c109'
down_revision = '5e0f2f775aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_doc', sa.String(), nullable=True))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_property_address', ['address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('unique_property_address', type_='unique')

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('lease_doc')

    # ### end Alembic commands ###
