"""add is_archived to property, invoice, and lease models

Revision ID: f2236bde7cf6
Revises: 3a911685c109
Create Date: 2024-12-16 18:14:44.479210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2236bde7cf6'
down_revision = '3a911685c109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
